version: '2.1'
services:

    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.0'
        environment:
            - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
            - discovery.type=single-node
        ports:
            - '9200:9200'
        volumes:
            - 'elasticsearch_data:/usr/share/elasticsearch/data'
        healthcheck:
            test: [CMD-SHELL, 'curl --silent --fail localhost:9200/_cluster/health || exit 1']
            interval: 30s
            timeout: 30s
            retries: 3

    kibana:
        image: 'docker.elastic.co/kibana/kibana:7.6.0'
        ports:
            - '5601:5601'
        depends_on:
            elasticsearch: {condition: service_healthy}

    logstash:
        image: 'docker.elastic.co/logstash/logstash:7.6.0'
        volumes:
            - './workspace/conf/logstash.yml:/usr/share/logstash/config/logstash.yml:ro'
            - './workspace/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro'
        depends_on:
            elasticsearch: {condition: service_healthy}

    filebeat:
        image: 'docker.elastic.co/beats/filebeat:7.6.0'
        volumes:
            - './workspace/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
            - './workspace/logs:/var/externallogs:ro'
        depends_on:
            elasticsearch: {condition: service_healthy}

volumes:
    elasticsearch_data: null
